<?php
//Available Sites:
$websites = array(
	'deviantart'	=> array('suffix'=>'.deviantart.com'),
	'facebook'		=> array('prefix'=>'www.facebook.com/'),
	'flickr'		=> array('prefix'=>'www.flickr.com/photos/'),
	'google'		=> array('prefix'=>'plus.google.com/'),
	'livejournal'	=> array('suffix'=>'.livejournal.com'),
	'reddit'		=> array('prefix'=>'www.reddit.com/user/'),
	'steam'			=> array('prefix'=>'steamcommunity.com/id/'),
	'tumblr'		=> array('suffix'=>'.tumblr.com'),
	'twitter'		=> array('prefix'=>'twitter.com/'),
	'youtube'		=> array('prefix'=>'www.youtube.com/'),
);
