<?php

/*

CREATE TABLE IF NOT EXISTS `mimetype` (
  `mime_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mime_ext` char(10) CHARACTER SET utf8mb4 NOT NULL,
  `mime_type` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
  `af_ext` char(4) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (`mime_id`),
  UNIQUE KEY `mime_ext` (`mime_ext`),
  KEY `mime_type` (`mime_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


SET @SQL_MODE = @@SQL_MODE;
SET @@SQL_MODE='NO_AUTO_VALUE_ON_ZERO';


INSERT INTO `mimetype`
(`mime_id`, `mime_ext`, `mime_type`, `af_ext`)

VALUES
(0,		'',			'application/octet-stream',			NULL),
(1,		'xhtml',	'application/xhtml+xml',			NULL),
(2,		'htm',		'text/html',						'html'),
(3,		'html',		'text/html',						NULL),
(4,		'sht',		'text/html',						NULL),
(5,		'shtm',		'text/html',						NULL),
(6,		'shtml',	'text/html',						NULL),
(7,		'stm',		'text/html',						NULL),
(8,		'wap',		'text/html',						NULL),
(9,		'css',		'text/css',							NULL),
(10,	'js',		'application/javascript',			NULL),
(11,	'xml',		'text/xml',							NULL),
(12,	'txt',		'text/plain',						NULL),
(13,	'rss',		'application/rss+xml',				NULL),
(14,	'swf',		'application/x-shockwave-flash',	NULL),
(15,	'bas',		'text/plain',						NULL),
(16,	'c',		'text/plain',						NULL),
(17,	'cs',		'text/plain',						NULL),
(18,	'cpp',		'text/plain',						NULL),
(19,	'h',		'text/plain',						NULL),
(20,	'pls',		'text/plain',						NULL),
(21,	'uls',		'text/iuls',						NULL),
(22,	'rtx',		'text/richtext',					NULL),
(23,	'sct',		'text/scriptlet',					NULL),
(24,	'tsv',		'text/tab-separated-values',		NULL),
(25,	'htt',		'text/webviewhtml',					NULL),
(26,	'323',		'text/h323',						NULL),
(27,	'htc',		'text/x-component',					NULL),
(28,	'etx',		'text/x-setext',					NULL),
(29,	'vcf',		'text/x-vcard',						NULL),
(30,	'jpe',		'image/jpeg',						'jpg'),
(31,	'jpg',		'image/jpeg',						NULL),
(32,	'jpeg',		'image/jpeg',						'jpg'),
(33,	'tif',		'image/tiff',						NULL),
(34,	'tiff',		'image/tiff',						'tif'),
(35,	'gif',		'image/gif',						NULL),
(36,	'png',		'image/png',						NULL),
(37,	'bmp',		'image/bmp',						NULL),
(38,	'ico',		'image/x-icon',						NULL),
(39,	'flr',		'x-world/x-vrml',					NULL),
(40,	'vrml',		'x-world/x-vrml',					NULL),
(41,	'wrl',		'x-world/x-vrml',					NULL),
(42,	'wrz',		'x-world/x-vrml',					NULL),
(43,	'xaf',		'x-world/x-vrml',					NULL),
(44,	'xof',		'x-world/x-vrml',					NULL),
(45,	'svg',		'image/svg+xml',					NULL),
(46,	'ief',		'image/ief',						NULL),
(47,	'cod',		'image/cis-cod',					NULL),
(48,	'jfif',		'image/pipeg',						NULL),
(49,	'pnm',		'image/x-portable-anymap',			NULL),
(50,	'pbm',		'image/x-portable-bitmap',			NULL),
(51,	'pgm',		'image/x-portable-graymap',			NULL),
(52,	'ppm',		'image/x-portable-pixmap',			NULL),
(53,	'ras',		'image/x-cmu-raster',				NULL),
(54,	'rgb',		'image/x-rgb',						NULL),
(55,	'xbm',		'image/x-xbitmap',					NULL),
(56,	'xpm',		'image/x-xpixmap',					NULL),
(57,	'xwd',		'image/x-xwindowdump',				NULL),
(58,	'psd',		'image/vnd.adobe.photoshop',		NULL),
(59,	'gz',		'application/x-gzip',				NULL),
(60,	'tar',		'application/octet-stream',			NULL),
(61,	'rar',		'application/x-rar-compressed',		NULL),
(62,	'bin',		'application/octet-stream',			NULL),
(63,	'class',	'application/octet-stream',			NULL),
(64,	'dms',		'application/octet-stream',			NULL),
(65,	'exe',		'application/octet-stream',			NULL),
(66,	'lha',		'application/octet-stream',			NULL),
(67,	'lzh',		'application/octet-stream',			NULL),
(68,	'com',		'application/octet-stream',			NULL),
(69,	'doc',		'application/msword',				NULL),
(70,	'dot',		'application/msword',				NULL),
(71,	'docx',		'application/vnd.openxmlformats-officedocument.wordprocessingml.document',	NULL),
(72,	'dotx',		'application/vnd.openxmlformats-officedocument.wordprocessingml.template',	NULL),
(73,	'docm',		'application/vnd.ms-word.document.macroEnabled.12',			NULL),
(74,	'dotm',		'application/vnd.ms-word.template.macroEnabled.12',			NULL),
(75,	'xls',		'application/vnd.ms-excel',			NULL),
(76,	'xlt',		'application/vnd.ms-excel',			NULL),
(77,	'xla',		'application/vnd.ms-excel',			NULL),
(78,	'xlsx',		'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',		NULL),
(79,	'xltx',		'application/vnd.openxmlformats-officedocument.spreadsheetml.template',		NULL),
(80,	'xlsm',		'application/vnd.ms-excel.sheet.macroEnabled.12',			NULL),
(81,	'xltm',		'application/vnd.ms-excel.template.macroEnabled.12',		NULL),
(82,	'xlam',		'application/vnd.ms-excel.addin.macroEnabled.12',			NULL),
(83,	'xlsb',		'application/vnd.ms-excel.sheet.binary.macroEnabled.12',	NULL),
(84,	'ppt',		'application/vnd.ms-powerpoint',	NULL),
(85,	'pot',		'application/vnd.ms-powerpoint',	NULL),
(86,	'pps',		'application/vnd.ms-powerpoint',	NULL),
(87,	'ppa',		'application/vnd.ms-powerpoint',	NULL),
(88,	'pptx',		'application/vnd.openxmlformats-officedocument.presentationml.presentation',	NULL),
(89,	'potx',		'application/vnd.openxmlformats-officedocument.presentationml.template',		NULL),
(90,	'ppsx',		'application/vnd.openxmlformats-officedocument.presentationml.slideshow',		NULL),
(91,	'ppam',		'application/vnd.ms-powerpoint.addin.macroEnabled.12',		NULL),
(92,	'pptm',		'application/vnd.ms-powerpoint.presentation.macroEnabled.12',	NULL),
(93,	'potm',		'application/vnd.ms-powerpoint.template.macroEnabled.12',	NULL),
(94,	'ppsm',		'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',	NULL),
(95,	'json',		'application/json',					NULL),
(96,	'jsonp',	'application/javascript',			NULL),
(97,	'csv',		'text/csv',							NULL),
(98,	'woff',		'font/woff',						NULL),
(99,	'woff2',	'font/woff2',						NULL),
(100,	'ttf',		'font/ttf',							NULL),
(101,	'otf',		'application/font-sfnt',			NULL),
(102,	'svgz',		'image/svg+xml',					NULL),
(103,	'asc',		'text/plain',						NULL),
(104,	'hpp',		'text/plain',						NULL),
(105,	'log',		'text/plain',						NULL),
(106,	'cnf',		'text/plain',						NULL),
(107,	'conf',		'text/plain',						NULL),
(108,	'text',		'text/plain',						'txt'),
(109,	'dtd',		'text/xml',							NULL),
(110,	'xhtm',		'application/xhtml+xml',			'xhtml'),
(111,	'xul',		'application/vnd.mozilla.xul+xml',	NULL),
(112,	'pdf',		'application/pdf',					NULL),
(113,	'torrent',	'application/x-bittorrent',			NULL),
(114,	'ps',		'application/postscript',			NULL),
(115,	'psb',		'image/vnd.adobe.photoshop',		NULL),
(116,	'7z',		'application/x-7z-compressed',		NULL),
(117,	'asf',		'video/x-ms-asf',					NULL),
(118,	'asx',		'video/x-ms-asf',					NULL),
(119,	'avi',		'video/x-msvideo',					NULL),
(120,	'bz2',		'application/x-bzip',				NULL),
(121,	'css.gz',	'text/css',							NULL),
(122,	'js.gz',	'application/javascript',			NULL),
(123,	'm3u',		'audio/x-mpegurl',					NULL),
(124,	'mov',		'video/quicktime',					NULL),
(125,	'mp3',		'audio/mpeg',						NULL),
(126,	'mpeg',		'video/mpeg',						NULL),
(127,	'mpg',		'video/mpeg',						NULL),
(128,	'ogg',		'application/ogg',					NULL),
(129,	'qt',		'video/quicktime',					NULL),
(130,	'tar.bz2',	'application/x-bzip-compressed-tar',	NULL),
(131,	'tar.gz',	'application/x-tgz',				NULL),
(132,	'tbz',		'application/x-bzip-compressed-tar',	NULL),
(133,	'wav',		'audio/x-wav',						NULL),
(134,	'wma',		'audio/x-ms-wma',					NULL),
(135,	'wmv',		'video/x-ms-wmv',					NULL),
(136,	'zip',		'application/zip',					NULL),
(137,	'tgz',		'application/x-tgz',				NULL);

SET @@SQL_MODE = @SQL_MODE;
*/
